services:
  backend:
    profiles: ["prod"]
    build:
      context: ./backend/eshop
      dockerfile: Dockerfile
    image: eshop-backend:prod
    working_dir: /app
    env_file:
      - ./backend/eshop/.env.docker
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "8080:8080"

  frontend:
    profiles: [ "prod" ]
    build:
      context: ./frontend/eshop
      dockerfile: Dockerfile
    image: vite-frontend:prod
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "3000:80"

  # Development services
  backend-dev:
    profiles: ["dev"]
    image: maven:3.9.6-eclipse-temurin-21
    working_dir: /app
    volumes:
      - ./backend/eshop:/app
      - ~/.m2:/root/.m2
    command: mvn spring-boot:run
    env_file:
      - ./backend/eshop/.env.docker
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "8080:8080"

  frontend-dev:
    profiles: [ "dev" ]
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend/eshop:/app
    command: sh -c "npm install && npm run dev"
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "3000:3000"